# Build stage
FROM node:20 AS build
WORKDIR /app

COPY package*.json ./
RUN npm install papaparse chart.js react-chartjs-2 react-loading-skeleton lucide-react lodash

COPY . .
RUN npm run build

# Serve stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

# Remove default nginx config
RUN rm /etc/nginx/conf.d/default.conf

# Simple SPA config
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
